version: '3.5'

services:

  web:
    build: .
    tty: true
    environment:
      APPLICATION_PORT: ${APPLICATION_PORT-3000}

  nginx:
    image: nginx:1.21-alpine
    ports:
      - ${NGINX_HOST_PORT:-8080}:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/
      APPLICATION_PORT: ${APPLICATION_PORT-3000}
    depends_on:
      - web
