version: '3.5'

services:
  nginx:
    image: nginx:1.21-alpine
    env_file:
      - .env
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - web
